const $=(selector,scope=document)=>scope.querySelector(selector);
const $$=(selector,scope=document)=>[...scope.querySelectorAll(selector)];
function toast(message){const old=$('.toast');if(old)old.remove();const el=document.createElement('div');el.className='toast';el.textContent=message;$('.app').append(el);setTimeout(()=>el.remove(),3000)}
$$('[data-go]').forEach(el=>el.addEventListener('click',()=>location.href=el.dataset.go));
$$('[data-role]').forEach(card=>card.addEventListener('click',()=>{const group=card.closest('[data-role-group]');$$('[data-role]',group).forEach(item=>{item.classList.remove('selected');const check=$('.role-check',item);if(check)check.remove()});card.classList.add('selected');const check=document.createElement('span');check.className='role-check';check.textContent='✓';card.append(check);group.dataset.selected=card.dataset.role;const continueButton=$('[data-role-continue]');if(continueButton)continueButton.disabled=false}));
const roleContinue=$('[data-role-continue]');if(roleContinue)roleContinue.addEventListener('click',()=>{const role=$('[data-role-group]').dataset.selected;const nested=location.pathname.includes('/adulto-mayor/')||location.pathname.includes('/colaborador/');location.href=role==='colaborador'?(nested?'../colaborador/inicio.html':'colaborador/inicio.html'):(nested?'../adulto-mayor/inicio.html':'adulto-mayor/inicio.html')});
$$('.quick-chip').forEach(chip=>chip.addEventListener('click',()=>{const input=$('.composer input');if(input){input.value=chip.textContent.trim();input.focus({preventScroll:true});setTimeout(syncVisualViewport,50)}}));
$$('[data-send]').forEach(button=>button.addEventListener('click',()=>{const composer=button.closest('.composer');const input=$('input',composer);if(!input.value.trim())return;const list=$('.messages');const bubble=document.createElement('div');bubble.className='bubble outgoing';bubble.textContent=input.value.trim();list.append(bubble);input.value='';list.scrollIntoView({behavior:'smooth',block:'end'});setTimeout(()=>{const reply=document.createElement('div');reply.className='bubble incoming';reply.textContent='Gracias. He registrado la información y continuaremos con tu solicitud.';list.append(reply);reply.scrollIntoView({behavior:'smooth',block:'end'})},550)}));
$$('.composer input').forEach(input=>input.addEventListener('keydown',event=>{if(event.key==='Enter')$('[data-send]',input.parentElement)?.click()}));
$$('.star').forEach((star,index,stars)=>star.addEventListener('click',()=>{$$('.star',star.parentElement).forEach((item,i)=>item.classList.toggle('on',i<=index));star.parentElement.dataset.rating=index+1}));
$$('[data-toast]').forEach(button=>button.addEventListener('click',()=>toast(button.dataset.toast)));
$$('.toggle').forEach(toggle=>toggle.addEventListener('click',()=>{toggle.classList.toggle('on');toggle.setAttribute('aria-pressed',toggle.classList.contains('on'));toast(toggle.classList.contains('on')?'Estás disponible para trabajar':'Disponibilidad desactivada')}));
$$('[data-filter]').forEach(tab=>tab.addEventListener('click',()=>{$$('[data-filter]').forEach(item=>item.classList.remove('active'));tab.classList.add('active');$$('[data-status]').forEach(card=>card.hidden=card.dataset.status!==tab.dataset.filter)}));
$$('[data-search]').forEach(input=>input.addEventListener('input',()=>{const query=input.value.toLowerCase();$$('[data-search-item]').forEach(item=>item.hidden=!item.textContent.toLowerCase().includes(query))}));
$$('[data-chat]').forEach(item=>item.addEventListener('click',()=>toast(`Abriendo conversación con ${item.dataset.chat}`)));
const conversationCatalog={adulto:{avam:{name:'AVAM Asistente',status:'Asistente virtual',avatar:'🤖',messages:[['in','Hola, Juan. Estoy aquí para ayudarte a solicitar apoyo de forma sencilla.'],['out','Necesito comprar medicamentos para mañana.'],['in','Entendido. Preparé la solicitud y encontré colaboradores jóvenes verificados cerca de tu farmacia.'],['in','Juan Rodríguez aceptó ayudarte. Puedes seguir el servicio desde Mis solicitudes.']]},juan:{name:'Juan Rodríguez',status:'Colaborador verificado · En servicio',avatar:'JR',messages:[['in','Hola, señor Juan. Soy el colaborador que aceptó su solicitud.'],['out','Muchas gracias. La receta está lista.'],['in','Ya estoy en la Farmacia Metro comprando los medicamentos.'],['in','En unos minutos salgo hacia su dirección.']]},carla:{name:'Carla Méndez',status:'Colaboradora verificada',avatar:'CM',messages:[['in','Hola, don Juan. Ya terminé la compra del supermercado.'],['out','Excelente, muchas gracias por la ayuda.'],['in','Con gusto. Revisé la lista completa y voy en camino.']]},soporte:{name:'Soporte AVAM',status:'Equipo de seguridad y ayuda',avatar:'SA',messages:[['in','Hola, Juan. ¿Necesitas ayuda con alguna solicitud?'],['out','Quería confirmar que el colaborador está verificado.'],['in','Sí. Todos los colaboradores visibles en AVAM completaron la verificación de identidad.']]}} ,colaborador:{juan:{name:'Juan Pérez',status:'Adulto mayor · Servicio activo',avatar:'JP',messages:[['in','Hola, María. Gracias por aceptar mi solicitud.'],['out','Con gusto, don Juan. Ya voy hacia la farmacia.'],['in','Perfecto. La receta está en recepción.'],['out','Entendido. Le avisaré cuando tenga los medicamentos.']]},marta:{name:'Marta Gómez',status:'Adulto mayor · Servicio completado',avatar:'MG',messages:[['in','Gracias por ayudarme con el supermercado.'],['out','Fue un gusto ayudarla, señora Marta.'],['in','Todo llegó completo y en muy buen estado.']]},roberto:{name:'Roberto López',status:'Adulto mayor · Solicitud pendiente',avatar:'RL',messages:[['in','Hola, María. ¿Podrías confirmar la hora de entrega?'],['out','Sí, don Roberto. Puedo entregar su pedido antes de las 4:00 p.m.'],['in','Perfecto, muchas gracias por confirmarlo.']]},soporte:{name:'Soporte AVAM',status:'Equipo de colaboradores',avatar:'SA',messages:[['in','Hola, María. Tu pago semanal fue procesado.'],['out','Gracias. ¿Cuándo estará disponible?'],['in','La transferencia debe reflejarse durante el próximo día hábil.']]}}};
function renderConversation(){const container=$('[data-conversation-messages]');if(!container)return;const role=document.body.dataset.conversationRole||'adulto';const key=new URLSearchParams(location.search).get('chat')||'avam';const conversation=conversationCatalog[role]?.[key]||conversationCatalog[role]?.soporte;const name=$('[data-conversation-name]');const status=$('[data-conversation-status]');const avatar=$('[data-conversation-avatar]');if(name)name.textContent=conversation.name;if(status)status.textContent=conversation.status;if(avatar)avatar.textContent=conversation.avatar;document.title=`AVAM | ${conversation.name}`;conversation.messages.forEach(([direction,message])=>{const bubble=document.createElement('div');bubble.className=`bubble ${direction==='out'?'outgoing':'incoming'}`;bubble.textContent=message;container.append(bubble)})}
renderConversation();
const visualViewport=window.visualViewport;
let viewportBaseline=visualViewport?.height||window.innerHeight;
function syncVisualViewport(){const height=visualViewport?.height||window.innerHeight;const width=visualViewport?.width||window.innerWidth;const top=visualViewport?.offsetTop||0;const left=visualViewport?.offsetLeft||0;const fieldFocused=document.activeElement?.matches('input, textarea, [contenteditable="true"]');if(!fieldFocused)viewportBaseline=Math.max(viewportBaseline,height);const keyboardOpen=Boolean(fieldFocused&&(viewportBaseline-height>120||height<window.innerHeight*.8));const root=document.documentElement.style;root.setProperty('--visual-viewport-height',`${Math.round(height)}px`);root.setProperty('--visual-viewport-width',`${Math.round(width)}px`);root.setProperty('--visual-viewport-top',`${Math.round(top)}px`);root.setProperty('--visual-viewport-left',`${Math.round(left)}px`);document.body.classList.toggle('keyboard-open',keyboardOpen)}
visualViewport?.addEventListener('resize',syncVisualViewport);
visualViewport?.addEventListener('scroll',syncVisualViewport);
window.addEventListener('orientationchange',()=>setTimeout(()=>{viewportBaseline=visualViewport?.height||window.innerHeight;syncVisualViewport()},250));
document.addEventListener('focusin',()=>setTimeout(syncVisualViewport,50));
document.addEventListener('focusout',()=>setTimeout(syncVisualViewport,250));
syncVisualViewport();
